variables:
- group: crm-internal-dev-services

name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  paths:
    include:
      - packages/frontend/*
  branches:
    include:
      - develop
  tags:
    exclude:
      - '*'

pool:
  name: aks-pool-frontend

resources:
  repositories:
  - repository: plataforma
    type: git
    name: plataforma

extends:
  template: pipelines/frontend/static/frontend-static-cd-homologacao2.yaml@plataforma
  parameters:
    tls_secret: $(TLS_SECRET)