variables:
- group: crm-internal-prod-services

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  name: aks-pool-frontend

resources:
  repositories:
    - repository: plataforma
      type: git
      name: plataforma

extends:
  template: pipelines/frontend/bff/frontend-bff-cd-prod.yaml@plataforma
  parameters:
    tls_secret: $(TLS_SECRET)
