variables:
- group: crm-internal-dev-services

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  name: aks-pool-frontend

resources:
  repositories:
  - repository: plataforma
    type: git
    name: plataforma

extends:
  template: pipelines/frontend/bff/frontend-bff-cd-desenvolvimento.yaml@plataforma
  parameters:
    sourceBranch: '$(Build.SourceBranch)' 
    sourceVersion: '$(Build.SourceVersion)'
    tls_secret: $(TLS_SECRET)